# Generated by Django 4.0.5 on 2022-08-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prof',
        ),
    ]
